# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'BlueToothDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

  # Pods for BlueToothDemo
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'BabyBluetooth'
    pod 'ReactiveCocoa'
  target 'BlueToothDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlueToothDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
